[package]
name = "bevy_rl_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
rand = "0.8.5"
bracket-lib = "0.8.1"

[profile.dev.package."*"]
opt-level = 3